version: '3.4'

services:
  financialcommitments.api:
    image: ${DOCKER_REGISTRY-}financialcommitmentsapi
    restart: always
    build:
      context: .
      dockerfile: FinancialCommitments.Api/Dockerfile    
    depends_on:
      - mongodb
      - rabbitmq
    ports:
      - "5000:80"
    environment:
      ConnectionStrings__MongoDB: "mongodb://root:example@localhost:27017"
      DatabaseSettings__DatabaseName: "FinanceDb"
      DatabaseSettings__CollectionName: "FinancialCommitments"
      TestMongoDatabase__Host: mongodb
      ASPNERTCORE_ENVIRONMENT: Development
    networks:
      - financialcommitments-network

  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT:-mongodb}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD:-mongodb}
      MONGO_INITDB_ROOT_DATABASE: ${MONGO_ROOT_DB:-mongodb}
      SALES_PASSWORD: ${SALES_PASSWORD:-sales}
      WAREHOUSE_PASSWORD: ${WAREHOUSE_PASSWORD:-warehouse}
    networks:
      - financialcommitments-network
    volumes:
      - ./mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro
      - mongodb-data:/data/db
      - mongodb-log:/var/log/mongodb
  
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - financialcommitments-network

    # postgres:
    #     image: postgre
    #     # healthcheck:
    #     #   test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "postgres" ]
    #     restart: always
    #     environment:
    #       - DUMP_FILE_PATH=/tmp/dump-dev.sql
    #     # volumes:
    #     #   - ./scripts/02-restore.sh:/docker-entrypoint-initdb.d/02-restore.sh:ro
    #     #   - ./scripts/dump-dev.sql:/tmp/dump-dev.sql:ro
    #     ports:
    #       - 5432:5432
    
  # webapi:
  #   image: api
  #   container_name: api-infra
    # restart: always
    # ports:
    #   - ${POSTGRES_PORT}:5432
    # environment:
    #   POSTGRES_DB: ${POSTGRES_DB}
    #   POSTGRES_USER: ${POSTGRES_USER}
    #   POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    #   POSTGRES_ROOT_PASSWORD: ${POSTGRES_ROOT_PASSWORD}
    # volumes:
    #   - ./scripts/dump-dev.sql:/tmp/dump-dev.sql:ro

volumes:
  mongodb-data:
    driver: local
  mongodb-log:
    driver: local
    
networks: 
    financialcommitments-network:
        name: ${MONGO_NETWORK:-mongodb.network}
        driver: bridge
