version: "3.9"

services:
    # postgres:
    #     image: postgre
    #     # healthcheck:
    #     #   test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "postgres" ]
    #     restart: always
    #     environment:
    #       - DUMP_FILE_PATH=/tmp/dump-dev.sql
    #     # volumes:
    #     #   - ./scripts/02-restore.sh:/docker-entrypoint-initdb.d/02-restore.sh:ro
    #     #   - ./scripts/dump-dev.sql:/tmp/dump-dev.sql:ro
    #     ports:
    #       - 5432:5432
  webapi:
    image: api
    container_name: api-infra
    # restart: always
    # ports:
    #   - ${POSTGRES_PORT}:5432
    # environment:
    #   POSTGRES_DB: ${POSTGRES_DB}
    #   POSTGRES_USER: ${POSTGRES_USER}
    #   POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    #   POSTGRES_ROOT_PASSWORD: ${POSTGRES_ROOT_PASSWORD}
    # volumes:
    #   - ./scripts/dump-dev.sql:/tmp/dump-dev.sql:ro