FROM mcr.microsoft.com/dotnet/aspnet:7.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build
WORKDIR /Api
COPY ["Dotnet.Api.csproj", "Dotnet.Api/"]
RUN dotnet restore "Dotnet.Api/Dotnet.Api.csproj"
COPY . .
WORKDIR "/Api/Dotnet.Api"
RUN dotnet build "Dotnet.Api.csproj" -c Release -o /app/build

# Build runtime image
FROM mcr.microsoft.com/dotnet/aspnet:7.0
WORKDIR /App
COPY --from=build-env /App/out .
ENTRYPOINT ["dotnet", "DotNet.Api.dll"]